[package]
name = "sync_app_rust"
version = "0.1.28"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
google-drive3-fork = "1.0.10"
rusoto_core = {version = "0.39", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.39", default_features = false, features=["rustls"]}
s4 = { git = "https://github.com/ddboline/s4.git", branch = "upgrade_rusoto_0.39" }
url = "1.7"
dotenv = "0.14"
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2"]}
failure = "0.1"
subprocess = "0.1"
walkdir = "2.2"
rayon = "1.1"
checksums = "0.5"
chrono = "0.4"
tempfile = "3.0"
structopt = "0.2"
hyper = "0.10"
hyper-native-tls = "0.3.0"
yup-oauth2 = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.3"
maplit = "1.0"
mime = "0.2"
rand = "0.6"
percent-encoding = "1.0"
parking_lot = "0.8"
log = "0.4"
env_logger = "0.6"

[[bin]]
name = "sync-app-rust"
path = "src/main.rs"
doc = false
