[package]
name = "sync_app_rust"
version = "0.4.16"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"
actix-rt = "1.0"
sync_app_lib = {path = "sync_app_lib"}
sync_app_http = {path = "sync_app_http"}
gdrive_lib = {path="gdrive_lib"}
tokio = {version="0.2", features=["full"]}
anyhow = "1.0"

[workspace]
members = [
    "sync_app_http",
    "sync_app_lib",
    "gdrive_lib",
]

[[bin]]
name = "sync-app-rust"
path = "src/main.rs"
doc = false

[[bin]]
name = "sync-app-http"
path = "src/sync_rust_http.rs"
doc = false
