[package]
name = "sync_app_rust"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[dependencies]
google-drive3-fork = "1.0.10"
onedrive-api = "0.4.0"
rusoto_core = {version = "0.36", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.36", default_features = false, features=["rustls"]}
s4 = { git = "https://github.com/ddboline/s4.git", branch = "upgrade_rusoto_0.36" }
url = "1.7"
dotenv = "0.14"
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2"]}
failure = "0.1"
subprocess = "0.1"
walkdir = "2.2"
rayon = "1.0"
checksums = "0.5"
chrono = "0.4"
tempfile = "3.0"
structopt = "0.2"

[[bin]]
name = "sync-app-rust"
path = "src/main.rs"
doc = false
