[package]
name = "sync_app_lib"
version = "0.5.16"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdrive_lib = {path="../gdrive_lib"}
rusoto_core = {version = "0.45", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.45", default_features = false, features=["rustls"]}
s3-ext = "0.1"
sts_profile_auth = "0.5"
url = "2.1"
dotenv = "0.15"
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
walkdir = "2.3"
rayon = "1.4"
checksums = "0.6"
chrono = "0.4"
structopt = "0.3"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
lazy_static = "1.4"
maplit = "1.0"
mime = "0.3"
rand = "0.7"
percent-encoding = "2.1"
parking_lot = "0.11"
log = "0.4"
reqwest = {version="0.10", features=["cookies", "json"]}
crossbeam-utils = "0.7"
anyhow = "1.0"
thiserror = "1.0"
dirs = "3.0"
derive_more = "0.99"
tokio = {version="0.2", features=["full"]}
async-trait = "0.1"
futures = "0.3"
itertools = "0.9"
envy = "0.4"
tempfile = "3.1"
smallvec = "1.4"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.3", features=["diesel_types"] }
