[package]
name = "sync_app_lib"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-drive3-fork = "1.0.10"
rusoto_core = {version = "0.40", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.40", default_features = false, features=["rustls"]}
s4 = { git = "https://github.com/ddboline/s4.git", branch = "upgrade_rusoto_0.40" }
url = "2.1"
dotenv = "0.15"
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
failure = "0.1"
subprocess = "0.1"
walkdir = "2.2"
rayon = "1.2"
checksums = "0.6"
chrono = "0.4"
tempfile = "3.1"
structopt = "0.3"
hyper = "0.10"
hyper-native-tls = "0.3.0"
yup-oauth2 = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
maplit = "1.0"
mime = "0.2"
rand = "0.7"
percent-encoding = "2.1"
parking_lot = "0.9"
log = "0.4"
env_logger = "0.7"
retry = "0.5"
actix = "0.8.3"
