[package]
name = "sync_app_lib"
version = "0.3.1"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdrive_lib = {path="../gdrive_lib"}
rusoto_core = {version = "0.42", default_features = false, features=["rustls"]}
rusoto_s3 = {version = "0.42", default_features = false, features=["rustls"]}
s4 = { git = "https://github.com/ddboline/s4.git", branch = "upgrade_rusoto_0.42" }
url = "2.1"
dotenv = "0.15"
r2d2 = "0.8"
diesel = {version="1.4", features=["postgres", "r2d2", "chrono"]}
failure = "0.1"
subprocess = "0.1"
walkdir = "2.2"
rayon = "1.3"
checksums = "0.6"
chrono = "0.4"
tempfile = "3.1"
structopt = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
maplit = "1.0"
mime = "0.3"
rand = "0.7"
percent-encoding = "2.1"
parking_lot = "0.10"
log = "0.4"
env_logger = "0.7"
retry = "0.5"
reqwest = {version="0.10", features=["cookies", "blocking", "json"]}
crossbeam-utils = "0.7"
sts_profile_auth = { git = "https://github.com/ddboline/sts_profile_auth.git", tag="0.1.3" }
