[package]
name = "sync_app_http"
version = "0.7.29"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rweb = {version="0.12", features=["openapi"]}
http = "0.2"
chrono = "0.4"
lazy_static = "1.4"
parking_lot = "0.11"
sync_app_lib = {path = "../sync_app_lib"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = {version="1.9", features=["time"]}
futures = "0.3"
url = "2.2"
anyhow = "1.0"
thiserror = "1.0"
maplit = "1.0"
async-trait = "0.1"
log = "0.4"
dirs = "3.0"
itertools = "0.10"
indexmap = "1.6"
serde_yaml = "0.8"
stdout-channel = "0.4"
rweb_helper = { git = "https://github.com/ddboline/rweb_helper.git", tag="0.2.2" }
stack-string = { version="0.2", features=["diesel_types", "rweb-openapi"] }
authorized_users = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.5.13"}
