[package]
name = "sync_app_http"
version = "0.5.18"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0"
actix = "0.10"
actix-identity = "0.3"
actix-rt = "1.1"
chrono = "0.4"
lazy_static = "1.4"
parking_lot = "0.11"
sync_app_lib = {path = "../sync_app_lib"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = {version="0.2", features=["time"]}
futures = "0.3"
url = "2.1"
anyhow = "1.0"
thiserror = "1.0"
actix-threadpool = "0.3"
maplit = "1.0"
async-trait = "0.1"
log = "0.4"
dirs = "3.0"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.6", features=["diesel_types"] }
auth_server_rust = { git = "https://github.com/ddboline/auth_server_rust.git", tag="0.1.4"}
